/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vulchivivek' at '10/2/17 4:26 PM' with Gradle 2.14.1
 *
 * @author vulchivivek, @date 10/2/17 4:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
